version: '3.7'

services:
  frontend:
    container_name: dionysius-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:80
  backend:
    container_name: dionysius-backend
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
